In [3]:
import pandas as pd
#Reading csv file
uber_data=pd.read_csv("Uber_Drives_2016.csv")
uber_data.head()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit

In [4]:
#shape of a Dataframe
print(uber_data.shape)

(1156, 7)

In [5]:
#info about the Dataframe (columns, Datatype
print(uber_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   START_DATE*  1156 non-null   object
 1   END_DATE*    1155 non-null   object
 2   CATEGORY*    1155 non-null   object
 3   START*       1155 non-null   object
 4   STOP*        1155 non-null   object
 5   MILES*       1156 non-null   float64
 6   PURPOSE*     653 non-null    object
dtypes: float64(1), object(6)
memory usage: 63.3+ KB
None

In [6]:
# Checking for null values
print(uber_data.isnull().sum())

START_DATE*      0
END_DATE*        1
CATEGORY*        1
START*           1
STOP*            1
MILES*           0
PURPOSE*       503
dtype: int64

In [7]:
null_rows = uber_data[uber_data.isnull().any(axis = 1)]
print(null_rows)

           START_DATE*         END_DATE* CATEGORY*            START*  \
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce
32      1/19/2016 9:09    1/19/2016 9:23  Business       Whitebridge
85      2/9/2016 10:54    2/9/2016 11:07  Personal       Whitebridge
86      2/9/2016 11:43    2/9/2016 11:50  Personal        Northwoods
87      2/9/2016 13:36    2/9/2016 13:52  Personal        Tanglewood
...                ...               ...       ...               ...
1066  12/19/2016 14:37  12/19/2016 14:50  Business  Unknown Location
1069  12/19/2016 19:05  12/19/2016 19:17  Business         Islamabad
1071   12/20/2016 8:49   12/20/2016 9:24  Business  Unknown Location
1143  12/29/2016 20:53  12/29/2016 21:42  Business           Kar?chi
1155            Totals               NaN       NaN               NaN

                    STOP*   MILES* PURPOSE*
1             Fort Pierce      5.0      NaN
32    Lake Wellingborough      7.2      NaN
85             Northwoods      5.3      NaN
86             Tanglewood      3.0      NaN
87                Preston      5.1      NaN
...                   ...      ...      ...
1066     Unknown Location      5.4      NaN
1069     Unknown Location      2.2      NaN
1071           Rawalpindi     12.0      NaN
1143     Unknown Location      6.4      NaN
1155                  NaN  12204.7      NaN

[503 rows x 7 columns]

In [8]:
null_rows = uber_data[uber_data['START_DATE*'].isnull()]
print(null_rows)

Empty DataFrame
Columns: [START_DATE*, END_DATE*, CATEGORY*, START*, STOP*, MILES*, PURPOSE*]
Index: []

In [9]:
uber_data = uber_data.rename(columns = {'START_DATE*' : 'START_DATE', 'END_DATE*' : 'END_DATE', 'START*' : 'START'})
uber_data

,START_DATE,END_DATE,CATEGORY*,START,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
...,...,...,...,...,...,...,...
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [10]:
# Display first 5 rows
uber_data.head(5)

,START_DATE,END_DATE,CATEGORY*,START,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit

In [11]:
# Display last 5 rows
uber_data.tail(5)

,START_DATE,END_DATE,CATEGORY*,START,STOP*,MILES*,PURPOSE*
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [12]:
# Display fist row
uber_data.iloc[0]

START_DATE    1/1/2016 21:11
END_DATE      1/1/2016 21:17
CATEGORY*           Business
START            Fort Pierce
STOP*            Fort Pierce
MILES*                   5.1
PURPOSE*      Meal/Entertain
Name: 0, dtype: object

In [13]:
# Display rows between 2 to 8
uber_data.iloc[2:8]

,START_DATE,END_DATE,CATEGORY*,START,STOP*,MILES*,PURPOSE*
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting

In [14]:
# Display rows 2 to 7
uber_data.iloc[2:8,1:3]

         END_DATE CATEGORY*
2  1/2/2016 20:38  Business
3  1/5/2016 17:45  Business
4  1/6/2016 15:49  Business
5  1/6/2016 17:19  Business
6  1/6/2016 17:35  Business
7  1/7/2016 13:33  Business

In [15]:
import pandas as pd
#Reading csv file
uber_data=pd.read_csv("Uber_Drives_2016.csv")
uber_data.head()
uber_data['START_DATE*']

0         1/1/2016 21:11
1          1/2/2016 1:25
2         1/2/2016 20:25
3         1/5/2016 17:31
4         1/6/2016 14:42
              ...
1151    12/31/2016 13:24
1152    12/31/2016 15:03
1153    12/31/2016 21:32
1154    12/31/2016 22:08
1155              Totals
Name: START_DATE*, Length: 1156, dtype: object

In [16]:
# Display first 1,2,3 row and starting column,stop and miles
uber_data.loc[[1,2,3],['START*','STOP*','MILES*']]

        START*        STOP*  MILES*
1  Fort Pierce  Fort Pierce     5.0
2  Fort Pierce  Fort Pierce     4.8
3  Fort Pierce  Fort Pierce     4.7

In [17]:
temp=pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40],'C':['2025-1-19','2025-1-21','2025-1-11','2025-1-22']})
temp

   A   B          C
0  1  10  2025-1-19
1  2  20  2025-1-21
2  3  30  2025-1-11
3  4  40  2025-1-22

In [18]:
temp=pd.DataFrame({'A':[1,2,3,4],'B':[10,20,30,40],'C':['2025-1-19','2025-1-21','2025-1-11','2025-1-22']})
temp.dtypes

A     int64
B     int64
C    object
dtype: object

In [19]:
#to convert str datatype into datetime format
temp['C'] = pd.to_datetime(temp['C'])
temp.dtypes

A             int64
B             int64
C    datetime64[ns]
dtype: object

In [20]:
# To convert int datatype into str datatype
temp['A'] = temp['A'].astype(str)
temp.dtypes

A            object
B             int64
C    datetime64[ns]
dtype: object

In [21]:
# convert the  datatype in dateformat
temp['C'] = pd.to_datetime(temp['C'],format="%d-%m-%y", errors = 'coerce')
temp.dtypes

A            object
B             int64
C    datetime64[ns]
dtype: object

In [22]:
#Boolean Indexing and Filtering
a = uber_data[uber_data['MILES*'] < 1]
a

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting
44,1/26/2016 17:27,1/26/2016 17:29,Business,Cary,Cary,0.5,Errand/Supplies
120,2/17/2016 16:38,2/17/2016 16:43,Business,Katunayaka,Katunayaka,0.5,Errand/Supplies
189,3/4/2016 16:16,3/4/2016 16:22,Business,Fayetteville Street,Depot Historic District,0.8,Errand/Supplies
212,3/11/2016 10:29,3/11/2016 10:36,Business,Congress Ave District,Downtown,0.8,NaN
258,3/21/2016 16:05,3/21/2016 16:13,Business,Downtown,Midtown,0.9,Meal/Entertain
292,4/1/2016 16:52,4/1/2016 16:57,Personal,Kissimmee,Kissimmee,0.7,NaN
418,6/8/2016 14:31,6/8/2016 14:37,Business,Medical Centre,Tudor City,0.7,Errand/Supplies
420,6/8/2016 17:16,6/8/2016 17:18,Business,Soho,Tribeca,0.5,Errand/Supplies
421,6/8/2016 17:59,6/8/2016 18:05,Business,Tribeca,Financial District,0.9,Errand/Supplies
516,7/5/2016 16:48,7/5/2016 16:52,Business,Whitebridge,Whitebridge,0.6,Errand/Supplies
567,7/18/2016 20:28,7/18/2016 20:32,Business,Hazelwood,Weston,0.9,Errand/Supplies
725,8/27/2016 12:12,8/27/2016 12:17,Business,Lahore,Lahore,0.9,NaN
758,9/13/2016 16:56,9/13/2016 17:02,Business,Unknown Location,Unknown Location,0.7,NaN
759,9/14/2016 11:55,9/14/2016 11:59,Business,Unknown Location,Unknown Location,0.7,NaN
760,9/15/2016 20:33,9/15/2016 20:38,Business,Unknown Location,Unknown Location,0.9,NaN
807,10/13/2016 13:02,10/13/2016 13:02,Business,Islamabad,Islamabad,0.7,NaN
923,11/9/2016 15:58,11/9/2016 16:04,Business,NOMA,Downtown,0.9,NaN
925,11/9/2016 18:09,11/9/2016 18:14,Business,Sunnyside,Ingleside,0.7,NaN
935,11/10/2016 19:18,11/10/2016 19:21,Business,West Berkeley,Central,0.8,NaN
945,11/12/2016 13:46,11/12/2016 13:50,Business,Central,West Berkeley,0.6,NaN
947,11/12/2016 15:14,11/12/2016 15:21,Business,South,Southwest Berkeley,0.8,NaN
955,11/13/2016 13:05,11/13/2016 13:11,Business,Southside,South Berkeley,0.9,NaN
956,11/13/2016 13:14,11/13/2016 13:18,Business,South Berkeley,Southside,0.9,NaN
1062,12/19/2016 13:04,12/19/2016 13:08,Business,Rawalpindi,Unknown Location,0.7,Errand/Supplies
1110,12/24/2016 22:04,12/24/2016 22:09,Business,Lahore,Lahore,0.6,Errand/Supplies
1111,12/25/2016 0:10,12/25/2016 0:14,Business,Lahore,Lahore,0.6,Errand/Supplies
1121,12/27/2016 12:53,12/27/2016 12:57,Business,Kar?chi,Kar?chi,0.6,Meal/Entertain
1149,12/30/2016 23:06,12/30/2016 23:10,Business,Kar?chi,Kar?chi,0.8,Customer Visit
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting

In [23]:
# if you need miles clumn whose values >6
df2=uber_data.loc[uber_data['MILES*']>6,['MILES*']]          
df2

       MILES*
4        63.7
6         7.1
8         8.3
9        16.5
10       10.8
...       ...
1144     12.9
1152     16.2
1153      6.4
1154     48.2
1155  12204.7

[569 rows x 1 columns]

In [24]:
 # if you need all the columns where miles>6
df3=uber_data.loc[uber_data['MILES*']>6]          
df3

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Customer Visit
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
...,...,...,...,...,...,...,...
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [25]:
uber_data.loc[uber_data['START*'] == "New York"]

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting
106,2/14/2016 16:35,2/14/2016 17:02,Business,New York,Long Island City,13.0,Meeting
423,6/10/2016 15:19,6/10/2016 16:28,Business,New York,Jamaica,16.3,Meeting

In [26]:
uber_data.loc[uber_data['START*'].isin(['New York','Cary'])]

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meal/Entertain
...,...,...,...,...,...,...,...
1049,12/13/2016 20:20,12/13/2016 20:29,Business,Cary,Cary,4.1,Meal/Entertain
1050,12/14/2016 16:52,12/14/2016 17:10,Business,Cary,Cary,3.4,NaN
1051,12/14/2016 17:22,12/14/2016 17:34,Business,Cary,Cary,3.3,NaN
1052,12/14/2016 17:50,12/14/2016 18:00,Business,Cary,Morrisville,3.0,Meal/Entertain
1054,12/15/2016 14:20,12/15/2016 14:54,Business,Cary,Morrisville,10.6,Meeting

In [27]:
df1 = uber_data.loc[(uber_data['MILES*'] > 10) & (uber_data['START*'].isin(['Cary', 'Morrisville']))]
df1

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meal/Entertain
34,1/20/2016 10:36,1/20/2016 11:11,Business,Cary,Raleigh,17.1,Meeting
46,1/27/2016 10:19,1/27/2016 10:48,Business,Cary,Raleigh,18.7,Customer Visit
50,1/28/2016 12:28,1/28/2016 13:00,Business,Cary,Raleigh,19.0,Temporary Site
55,1/29/2016 11:43,1/29/2016 12:03,Business,Cary,Durham,10.4,Meeting
...,...,...,...,...,...,...,...
990,11/22/2016 15:51,11/22/2016 16:43,Business,Cary,Cary,12.7,Customer Visit
997,11/25/2016 11:47,11/25/2016 12:04,Business,Cary,Durham,10.3,Meeting
1035,12/9/2016 22:03,12/9/2016 22:57,Business,Cary,Cary,18.9,Customer Visit
1036,12/10/2016 12:43,12/10/2016 13:16,Business,Cary,Fuquay-Varina,15.6,Meeting
1054,12/15/2016 14:20,12/15/2016 14:54,Business,Cary,Morrisville,10.6,Meeting

# Sort

In [29]:
# by default it returns ASC order
uber_data.sort_values(by = 'MILES*')

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
120,2/17/2016 16:38,2/17/2016 16:43,Business,Katunayaka,Katunayaka,0.5,Errand/Supplies
420,6/8/2016 17:16,6/8/2016 17:18,Business,Soho,Tribeca,0.5,Errand/Supplies
44,1/26/2016 17:27,1/26/2016 17:29,Business,Cary,Cary,0.5,Errand/Supplies
516,7/5/2016 16:48,7/5/2016 16:52,Business,Whitebridge,Whitebridge,0.6,Errand/Supplies
1111,12/25/2016 0:10,12/25/2016 0:14,Business,Lahore,Lahore,0.6,Errand/Supplies
...,...,...,...,...,...,...,...
776,9/27/2016 21:01,9/28/2016 2:37,Business,Unknown Location,Unknown Location,195.6,NaN
881,10/30/2016 15:22,10/30/2016 18:23,Business,Asheville,Mebane,195.9,NaN
270,3/25/2016 22:54,3/26/2016 1:39,Business,Jacksonville,Kissimmee,201.0,Meeting
269,3/25/2016 16:52,3/25/2016 22:22,Business,Latta,Jacksonville,310.3,Customer Visit
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [30]:
# by default it returns ASC order
uber_data.sort_values(by = 'MILES*',ascending = False)

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN
269,3/25/2016 16:52,3/25/2016 22:22,Business,Latta,Jacksonville,310.3,Customer Visit
270,3/25/2016 22:54,3/26/2016 1:39,Business,Jacksonville,Kissimmee,201.0,Meeting
881,10/30/2016 15:22,10/30/2016 18:23,Business,Asheville,Mebane,195.9,NaN
776,9/27/2016 21:01,9/28/2016 2:37,Business,Unknown Location,Unknown Location,195.6,NaN
...,...,...,...,...,...,...,...
1111,12/25/2016 0:10,12/25/2016 0:14,Business,Lahore,Lahore,0.6,Errand/Supplies
516,7/5/2016 16:48,7/5/2016 16:52,Business,Whitebridge,Whitebridge,0.6,Errand/Supplies
420,6/8/2016 17:16,6/8/2016 17:18,Business,Soho,Tribeca,0.5,Errand/Supplies
120,2/17/2016 16:38,2/17/2016 16:43,Business,Katunayaka,Katunayaka,0.5,Errand/Supplies
44,1/26/2016 17:27,1/26/2016 17:29,Business,Cary,Cary,0.5,Errand/Supplies

In [33]:
# by default it returns ASC order of multipile order
uber_data.sort_values(by = ['START*','MILES*'], ascending = [True,False])

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
906,11/4/2016 21:04,11/4/2016 21:20,Business,Agnew,Cory,4.3,NaN
911,11/6/2016 10:50,11/6/2016 11:04,Business,Agnew,Renaissance,2.4,NaN
908,11/5/2016 8:34,11/5/2016 8:43,Business,Agnew,Renaissance,2.2,NaN
910,11/5/2016 19:20,11/5/2016 19:28,Business,Agnew,Agnew,2.2,NaN
879,10/30/2016 12:58,10/30/2016 13:18,Business,Almond,Bryson City,15.2,NaN
...,...,...,...,...,...,...,...
889,11/1/2016 17:35,11/1/2016 17:42,Business,Whitebridge,Whitebridge,1.2,NaN
890,11/1/2016 19:14,11/1/2016 19:20,Business,Whitebridge,Whitebridge,1.0,NaN
516,7/5/2016 16:48,7/5/2016 16:52,Business,Whitebridge,Whitebridge,0.6,Errand/Supplies
870,10/28/2016 18:13,10/28/2016 20:07,Business,Winston Salem,Asheville,133.6,Meeting
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

# Conditionally adding columns

In [56]:
uber_data['price'] = 100;
uber_data

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*,price
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,100
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN,100
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,100
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting,100
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,100
...,...,...,...,...,...,...,...,...
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site,100
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting,100
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site,100
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site,100
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN,100

In [57]:
# Adding a separate column using conditional statement
import numpy as np 
uber_data["MILES_CAT"] = np.where(uber_data['MILES*'] > 100,"Long trip", "Short trip")
uber_data.head()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*,price,MILES_CAT
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,100,Short trip
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN,100,Short trip
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,100,Short trip
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting,100,Short trip
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,100,Short trip

In [58]:
condition = [(uber_data["MILES*"] > 100), (uber_data['MILES*'] > 50) & (uber_data['MILES*'] > 100), (uber_data['MILES*'] > 50)]
categories = ["Long trip", 'Medium trip', 'short trip']
uber_data["MILES_CAT"] = np.select(condition,categories, default = "Unkonow")
uber_data.drop(columns = ['MILES_CAT'], inplace = True)
uber_data.tail(50)

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*,price
1106,12/24/2016 12:51,12/24/2016 12:53,Business,Lahore,Lahore,1.6,Errand/Supplies,100
1107,12/24/2016 13:08,12/24/2016 13:29,Business,Lahore,Lahore,3.6,Errand/Supplies,100
1108,12/24/2016 17:12,12/24/2016 17:27,Business,Lahore,Lahore,1.7,Errand/Supplies,100
1109,12/24/2016 19:12,12/24/2016 19:27,Business,Lahore,Lahore,2.9,Meal/Entertain,100
1110,12/24/2016 22:04,12/24/2016 22:09,Business,Lahore,Lahore,0.6,Errand/Supplies,100
1111,12/25/2016 0:10,12/25/2016 0:14,Business,Lahore,Lahore,0.6,Errand/Supplies,100
1112,12/25/2016 19:15,12/25/2016 19:26,Business,Lahore,Lahore,2.3,Meal/Entertain,100
1113,12/25/2016 21:58,12/25/2016 22:04,Business,Lahore,Lahore,2.3,Meal/Entertain,100
1114,12/26/2016 8:30,12/26/2016 8:41,Business,Lahore,Lahore,3.2,Meal/Entertain,100
1115,12/26/2016 9:05,12/26/2016 9:19,Business,Lahore,Lahore,6.2,Customer Visit,100
1116,12/26/2016 10:15,12/26/2016 10:36,Business,Lahore,Lahore,7.7,Customer Visit,100
1117,12/26/2016 11:29,12/26/2016 11:42,Business,Lahore,Lahore,3.8,Customer Visit,100
1118,12/26/2016 13:09,12/26/2016 13:43,Business,Lahore,Unknown Location,7.9,Meeting,100
1119,12/27/2016 7:02,12/27/2016 7:14,Business,Kar?chi,Kar?chi,4.9,Temporary Site,100
1120,12/27/2016 8:37,12/27/2016 8:59,Business,Kar?chi,Kar?chi,5.0,Meal/Entertain,100
1121,12/27/2016 12:53,12/27/2016 12:57,Business,Kar?chi,Kar?chi,0.6,Meal/Entertain,100
1122,12/27/2016 14:49,12/27/2016 15:03,Business,Kar?chi,Unknown Location,3.1,Customer Visit,100
1123,12/27/2016 16:34,12/27/2016 16:58,Business,Unknown Location,Kar?chi,7.9,Meeting,100
1124,12/27/2016 19:19,12/27/2016 19:50,Business,Kar?chi,Kar?chi,5.5,Customer Visit,100
1125,12/28/2016 8:34,12/28/2016 9:06,Business,Kar?chi,Unknown Location,10.3,Meal/Entertain,100
1126,12/28/2016 11:42,12/28/2016 12:12,Business,Unknown Location,Kar?chi,10.4,Errand/Supplies,100
1127,12/28/2016 13:53,12/28/2016 14:01,Business,Kar?chi,Kar?chi,2.0,Errand/Supplies,100
1128,12/28/2016 15:04,12/28/2016 15:39,Business,Kar?chi,Unknown Location,8.5,Meal/Entertain,100
1129,12/28/2016 17:02,12/28/2016 17:16,Business,Unknown Location,Kar?chi,4.4,Errand/Supplies,100
1130,12/28/2016 18:33,12/28/2016 18:56,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies,100
1131,12/28/2016 22:44,12/28/2016 23:18,Business,Kar?chi,Kar?chi,5.1,Errand/Supplies,100
1132,12/29/2016 0:49,12/29/2016 1:06,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies,100
1133,12/29/2016 9:44,12/29/2016 10:07,Business,Kar?chi,Unknown Location,11.6,Meal/Entertain,100
1134,12/29/2016 11:28,12/29/2016 12:00,Business,Unknown Location,Kar?chi,11.9,Meal/Entertain,100
1135,12/29/2016 12:25,12/29/2016 12:33,Business,Kar?chi,Kar?chi,1.4,Errand/Supplies,100
1136,12/29/2016 13:17,12/29/2016 13:24,Business,Kar?chi,Kar?chi,1.1,Errand/Supplies,100
1137,12/29/2016 13:56,12/29/2016 14:11,Business,Kar?chi,Kar?chi,4.1,Airport/Travel,100
1138,12/29/2016 14:42,12/29/2016 14:58,Business,Kar?chi,Kar?chi,6.1,Between Offices,100
1139,12/29/2016 15:05,12/29/2016 15:16,Business,Kar?chi,Kar?chi,1.3,Errand/Supplies,100
1140,12/29/2016 18:59,12/29/2016 19:14,Business,Kar?chi,Unknown Location,3.0,Meal/Entertain,100
1141,12/29/2016 19:50,12/29/2016 20:10,Business,Unknown Location,Kar?chi,4.1,Customer Visit,100
1142,12/29/2016 20:15,12/29/2016 20:45,Business,Kar?chi,Kar?chi,7.2,Meeting,100
1143,12/29/2016 20:53,12/29/2016 21:42,Business,Kar?chi,Unknown Location,6.4,NaN,100
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting,100
1145,12/30/2016 10:15,12/30/2016 10:33,Business,Kar?chi,Kar?chi,2.8,Errand/Supplies,100
1146,12/30/2016 11:31,12/30/2016 11:56,Business,Kar?chi,Kar?chi,2.9,Errand/Supplies,100
1147,12/30/2016 15:41,12/30/2016 16:03,Business,Kar?chi,Kar?chi,4.6,Errand/Supplies,100
1148,12/30/2016 16:45,12/30/2016 17:08,Business,Kar?chi,Kar?chi,4.6,Meeting,100
1149,12/30/2016 23:06,12/30/2016 23:10,Business,Kar?chi,Kar?chi,0.8,Customer Visit,100
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting,100
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site,100
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting,100
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site,100
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site,100
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN,100

# Group By

In [59]:
import pandas as pd

# Sample dataset
data = {
    'Employee': ['Asha', 'Ravi', 'Meena', 'Ravi', 'Asha', 'Meena', 'Ravi', 'Asha'],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'Finance', 'IT', 'HR'],
    'Sales': [20000, 30000, 25000, 40000, 20000, 27000, 35000, 22000],
     'Units': [2, 3, 2, 4, 2, 3, 4, 2],
    'Month': ['Jan', 'Jan', 'Jan', 'Feb', 'Feb', 'Feb', 'Mar', 'Mar']
}

df = pd.DataFrame(data)
print(df)

  Employee Department  Sales  Units Month
0     Asha         HR  20000      2   Jan
1     Ravi         IT  30000      3   Jan
2    Meena    Finance  25000      2   Jan
3     Ravi         IT  40000      4   Feb
4     Asha         HR  20000      2   Feb
5    Meena    Finance  27000      3   Feb
6     Ravi         IT  35000      4   Mar
7     Asha         HR  22000      2   Mar

In [60]:
c=df.groupby('Department')['Sales'].count()   # Count
print("<====================================Count========>")
print(c)
c=df.groupby('Department')['Sales'].sum()
print("<====================================Sum==========>")
print(c)
c=df.groupby('Department')['Sales'].mean()
print("<=====================================Mean==========>")
print(c)
c=df.groupby('Department')['Sales'].median()
print("<====================================Median==========>")
print(c)
c=df.groupby('Department')['Sales'].max()
print("<====================================Max==========>")
print(c)
c=df.groupby('Department')['Sales'].min()
print("<====================================Min==========>")
print(c)
c=df.groupby('Department')['Sales'].nunique()
print("<====================================Unique==========>")
print(c)

<====================================Count========>
Department
Finance    2
HR         3
IT         3
Name: Sales, dtype: int64
<====================================Sum==========>
Department
Finance     52000
HR          62000
IT         105000
Name: Sales, dtype: int64
<=====================================Mean==========>
Department
Finance    26000.000000
HR         20666.666667
IT         35000.000000
Name: Sales, dtype: float64
<====================================Median==========>
Department
Finance    26000.0
HR         20000.0
IT         35000.0
Name: Sales, dtype: float64
<====================================Max==========>
Department
Finance    27000
HR         22000
IT         40000
Name: Sales, dtype: int64
<====================================Min==========>
Department
Finance    25000
HR         20000
IT         30000
Name: Sales, dtype: int64
<====================================Unique==========>
Department
Finance    2
HR         2
IT         3
Name: Sales, dtype: int64

# 1) Built-in aggregate functions (single-column)

In [61]:
c=df.groupby('Department')['Sales'].agg(['sum','mean','median','count','max','min','nunique'])
c

               sum          mean   median  count    max    min  nunique
Department
Finance      52000  26000.000000  26000.0      2  27000  25000        2
HR           62000  20666.666667  20000.0      3  22000  20000        2
IT          105000  35000.000000  35000.0      3  40000  30000        3

# 2) Multiple aggregations on multiple columns (list / dict style)

## 2.1 List-style (same functions for each column)

In [62]:
c=df.groupby('Department')[['Sales','Units']].agg(['count','sum','mean','max','min'])
c

           Sales                                     Units                    \
           count     sum          mean    max    min count sum      mean max
Department
Finance        2   52000  26000.000000  27000  25000     2   5  2.500000   3
HR             3   62000  20666.666667  22000  20000     3   6  2.000000   2
IT             3  105000  35000.000000  40000  30000     3  11  3.666667   4


           min
Department
Finance      2
HR           2
IT           3

## 2.2 Dict-style (different functions per column)

In [63]:
c=df.groupby('Department').agg({
    'Sales':['sum','mean','max'],
    'Units':['count','max','min']
})
c

             Sales                      Units
               sum          mean    max count max min
Department
Finance      52000  26000.000000  27000     2   3   2
HR           62000  20666.666667  22000     3   2   2
IT          105000  35000.000000  40000     3   4   3

## 3) Named aggregation (clean column names, recommended)

In [64]:
c=df.groupby('Department').agg(
    total_sales = ('Sales', 'sum'),
    avg_sales   = ('Sales', 'mean'),
    max_sales   = ('Sales', 'max'),
    units_sold  = ('Units', 'sum'),
    avg_units   = ('Units', 'mean'),
    emp_count   = ('Employee', 'nunique')
).reset_index()
c

,Department,total_sales,avg_sales,max_sales,units_sold,avg_units,emp_count
0,Finance,52000,26000.000000,27000,5,2.500000,1
1,HR,62000,20666.666667,22000,6,2.000000,1
2,IT,105000,35000.000000,40000,11,3.666667,1