In [32]:
import pandas as pd 
data = pd.read_csv(r"C:/Users/Pranav/Downloads/transaction_data.csv.zip")

In [16]:
data.head() #It gives the top record of the excel data

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
0,278166,6355745,Sat Feb 02 12:50:00 IST 2019,465549,FAMILY ALBUM WHITE PICTURE FRAME,6,11.73,United Kingdom
1,337701,6283376,Wed Dec 26 09:06:00 IST 2018,482370,LONDON BUS COFFEE MUG,3,3.52,United Kingdom
2,267099,6385599,Fri Feb 15 09:45:00 IST 2019,490728,SET 12 COLOUR PENCILS DOLLY GIRL,72,0.90,France
3,380478,6044973,Fri Jun 22 07:14:00 IST 2018,459186,UNION JACK FLAG LUGGAGE TAG,3,1.73,United Kingdom
4,-1,6143225,Mon Sep 10 11:58:00 IST 2018,1733592,WASHROOM METAL SIGN,3,3.40,United Kingdom

In [17]:
data.tail()  #It gives the bottom record of the excel data

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
1083813,313131,6040298,Mon Jun 18 09:18:00 IST 2018,437976,DENIM PATCH PURSE PINK BUTTERFLY,30,2.28,EIRE
1083814,295743,6387117,Sat Feb 16 09:14:00 IST 2019,484113,RECYCLED ACAPULCO MAT PINK,6,11.39,United Kingdom
1083815,-1,6361817,Tue Feb 05 05:26:00 IST 2019,497595,DOILY THANK YOU CARD,15,1.15,United Kingdom
1083816,324765,5945500,Fri Mar 23 06:26:00 IST 2018,470883,REGENCY CAKESTAND 3 TIER,48,15.12,United Kingdom
1083817,351645,6118145,Tue Aug 21 08:21:00 IST 2018,471849,HEART OF WICKER SMALL,9,2.28,United Kingdom

In [18]:
data[50:150]  #Give the record between 50 to 150 |

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
50,-1,6149418,Sun Sep 16 11:31:00 IST 2018,474873,PACK OF 20 SPACEBOY NAPKINS,3,2.25,United Kingdom
51,371175,6183606,Mon Oct 15 06:45:00 IST 2018,440538,36 PENCILS TUBE SKULLS,48,1.73,United Kingdom
52,313992,6275643,Sun Dec 23 06:33:00 IST 2018,461664,PACK OF 12 PINK PAISLEY TISSUES,72,0.54,United Kingdom
53,327684,6288656,Sun Dec 30 10:47:00 IST 2018,465738,VICTORIAN GLASS HANGING T-LIGHT,18,2.70,United Kingdom
54,336420,6359661,Mon Feb 04 07:18:00 IST 2019,490455,HOT WATER BOTTLE KEEP CALM,12,6.84,United Kingdom
...,...,...,...,...,...,...,...,...
145,300258,6255425,Mon Dec 10 09:32:00 IST 2018,1787079,JUMBO BAG RED RETROSPOT,60,2.48,United Kingdom
146,330876,6037504,Sat Jun 16 10:00:00 IST 2018,486759,CLOCK MAGNET MUM'S KITCHEN,3,3.99,United Kingdom
147,305025,6352280,Fri Feb 01 07:37:00 IST 2019,455322,LARGE MEDINA STAMPED METAL BOWL,6,6.84,United Kingdom
148,-1,6108674,Tue Aug 14 07:12:00 IST 2018,1780905,wet damaged,-288,0.00,United Kingdom
149,364266,6092163,Tue Jul 31 07:41:00 IST 2018,482916,TRAVEL CARD WALLET VINTAGE TICKET,3,0.58,United Kingdom

In [20]:
data[:56]    #give the first 55 records

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
0,278166,6355745,Sat Feb 02 12:50:00 IST 2019,465549,FAMILY ALBUM WHITE PICTURE FRAME,6,11.73,United Kingdom
1,337701,6283376,Wed Dec 26 09:06:00 IST 2018,482370,LONDON BUS COFFEE MUG,3,3.52,United Kingdom
2,267099,6385599,Fri Feb 15 09:45:00 IST 2019,490728,SET 12 COLOUR PENCILS DOLLY GIRL,72,0.90,France
3,380478,6044973,Fri Jun 22 07:14:00 IST 2018,459186,UNION JACK FLAG LUGGAGE TAG,3,1.73,United Kingdom
4,-1,6143225,Mon Sep 10 11:58:00 IST 2018,1733592,WASHROOM METAL SIGN,3,3.40,United Kingdom
5,285957,6307136,Fri Jan 11 09:50:00 IST 2019,1787247,CUT GLASS T-LIGHT HOLDER OCTAGON,12,3.52,United Kingdom
6,345954,6162981,Fri Sep 28 10:51:00 IST 2018,471576,NATURAL SLATE CHALKBOARD LARGE,9,6.84,United Kingdom
7,-1,6143225,Mon Sep 10 11:58:00 IST 2018,447867,SKULLS WRITING SET,120,1.15,United Kingdom
8,339822,6255403,Mon Dec 10 09:23:00 IST 2018,1783845,MULTI COLOUR SILVER T-LIGHT HOLDER,36,1.18,United Kingdom
9,328440,6387425,Sat Feb 16 10:35:00 IST 2019,494802,SET OF 6 RIBBONS PERFECTLY PRETTY,36,3.99,United Kingdom
10,316848,6262696,Sat Dec 15 10:05:00 IST 2018,460215,RED HARMONICA IN BOX,36,1.73,United Kingdom
11,372897,6199061,Mon Oct 29 09:04:00 IST 2018,459669,WOODEN BOX OF DOMINOES,3,1.73,United Kingdom
12,364791,6358242,Sun Feb 03 09:25:00 IST 2019,486276,SET OF 5 MINI GROCERY MAGNETS,3,2.88,United Kingdom
13,-1,6058140,Mon Jul 02 07:33:00 IST 2018,435225,LUNCH BAG RED RETROSPOT,60,6.85,United Kingdom
14,321321,6254358,Mon Dec 10 05:43:00 IST 2018,455868,FOLDING UMBRELLA CREAM POLKADOT,12,6.84,United Kingdom
15,304353,6328674,Mon Jan 21 09:54:00 IST 2019,477246,ALARM CLOCK BAKELIKE GREEN,24,5.18,United Kingdom
16,369852,6075883,Sat Jul 21 08:14:00 IST 2018,477036,CARD CIRCUS PARADE,36,0.58,United Kingdom
17,-1,6288843,Sun Dec 30 12:58:00 IST 2018,489594,VINTAGE CHRISTMAS TABLECLOTH,3,34.45,United Kingdom
18,278985,6064025,Mon Jul 09 09:03:00 IST 2018,1771938,SET OF 3 HEART COOKIE CUTTERS,36,1.73,United Kingdom
19,331884,6223569,Sun Nov 18 11:14:00 IST 2018,461622,PACK OF 12 SUKI TISSUES,72,0.54,United Kingdom
20,335580,6031883,Mon Jun 11 11:05:00 IST 2018,476028,PINK BABY BUNTING,150,3.52,United Kingdom
21,364308,6257163,Tue Dec 11 07:39:00 IST 2018,434028,DISCO BALL CHRISTMAS DECORATION,72,0.17,United Kingdom
22,262269,5945093,Wed Mar 21 09:13:00 IST 2018,474726,WOODEN SKITTLES GARDEN SET,6,22.02,France
23,-1,6388019,Sat Feb 16 13:24:00 IST 2019,490329,ROLL WRAP VINTAGE CHRISTMAS,30,3.40,United Kingdom
24,-1,6212987,Sun Nov 11 08:02:00 IST 2018,443436,OWL DOORSTOP,3,11.45,United Kingdom
25,296016,6309336,Sat Jan 12 10:09:00 IST 2019,464751,FOOD CONTAINER SET 3 LOVE HEART,3,5.70,United Kingdom
26,373170,6101095,Mon Aug 06 08:34:00 IST 2018,452844,PINK HEART SHAPE LOVE BUCKET,15,4.08,United Kingdom
27,281568,6344448,Mon Jan 28 09:13:00 IST 2019,485667,FELTCRAFT GIRL NICOLE KIT,36,6.84,United Kingdom
28,-1,6217541,Wed Nov 14 05:26:00 IST 2018,469392,LUNCH BOX WITH CUTLERY RETROSPOT,3,6.85,United Kingdom
29,364266,6370276,Sat Feb 09 07:54:00 IST 2019,453348,RETROSPOT GIANT TUBE MATCHES,6,3.52,United Kingdom
30,-1,6212294,Sun Nov 11 06:29:00 IST 2018,482559,PANTRY WASHING UP BRUSH,6,4.55,United Kingdom
31,344253,6167568,Mon Oct 01 07:54:00 IST 2018,460656,RED RETROSPOT PICNIC BAG,6,4.08,United Kingdom
32,322371,6244425,Mon Dec 03 11:54:00 IST 2018,488019,SET OF 4 KNICK KNACK TINS POPPIES,18,5.73,United Kingdom
33,366051,5968743,Fri Apr 13 10:36:00 IST 2018,441735,SET/2 RED RETROSPOT TEA TOWELS,9,4.08,United Kingdom
34,291753,5984385,Sun Apr 29 07:30:00 IST 2018,472647,MEMO BOARD RETROSPOT DESIGN,12,6.84,United Kingdom
35,355383,6335252,Fri Jan 25 06:35:00 IST 2019,435204,RED RETROSPOT CHARLOTTE BAG,30,1.18,United Kingdom
36,-1,5934412,Sat Mar 03 06:14:00 IST 2018,436380,BLACK EAR MUFF HEADPHONES,3,15.21,United Kingdom
37,-1,5952144,Tue Mar 27 10:29:00 IST 2018,434973,JUMBO BAG OWLS,12,5.70,United Kingdom
38,364098,6090810,Mon Jul 30 11:35:00 IST 2018,475839,LUNCH BOX I LOVE LONDON,9,2.70,United Kingdom
39,380478,5976399,Sat Apr 21 08:05:00 IST 2018,1784370,HANGING HEART ZINC T-LIGHT HOLDER,6,1.18,United Kingdom
40,341355,5940143,Sun Mar 18 07:30:00 IST 2018,476007,RECIPE BOX RETROSPOT,15,4.08,United Kingdom
41,344946,6383036,Wed Feb 13 08:59:00 IST 2019,469875,AIRLINE BAG VINTAGE JET SET BROWN,3,5.87,United Kingdom
42,271341,5995253,Wed May 09 10:25:00 IST 2018,445452,PACK OF 72 RETROSPOT CAKE CASES,72,0.76,United Kingdom
43,-1,5925458,Sat Feb 24 12:46:00 IST 2018,440370,PINK FLORAL FELTCRAFT SHOULDER BAG,3,5.18,United Kingdom
44,259854,6339795,Sat Jan 26 11:37:00 IST 2019,1784832,72 SWEETHEART FAIRY CAKE CASES,72,0.76,Austria
45,-1,6079370,Sun Jul 22 11:06:00 IST 2018,456351,RED TOADSTOOL LED NIGHT LIGHT,3,5.70,United Kingdom
46,336693,6197884,Sun Oct 28 09:50:00 IST 2018,459963,MAN FLU METAL SIGN,6,2.90,United Kingdom
47,308280,5962924,Sun Apr 08 08:31:00 IST 2018,435288,LUNCH BAG CARS BLUE,90,2.28,United Kingdom
48,377937,6226627,Tue Nov 20 11:16:00 IST 2018,444759,NO JUNK MAIL METAL SIGN,72,0.54,United Kingdom
49,318969,6150430,Mon Sep 17 08:56:00 IST 2018,454818,GLASS BEURRE DISH,72,4.68,United Kingdom
50,-1,6149418,Sun Sep 16 11:31:00 IST 2018,474873,PACK OF 20 SPACEBOY NAPKINS,3,2.25,United Kingdom
51,371175,6183606,Mon Oct 15 06:45:00 IST 2018,440538,36 PENCILS TUBE SKULLS,48,1.73,United Kingdom
52,313992,6275643,Sun Dec 23 06:33:00 IST 2018,461664,PACK OF 12 PINK PAISLEY TISSUES,72,0.54,United Kingdom
53,327684,6288656,Sun Dec 30 10:47:00 IST 2018,465738,VICTORIAN GLASS HANGING T-LIGHT,18,2.70,United Kingdom
54,336420,6359661,Mon Feb 04 07:18:00 IST 2019,490455,HOT WATER BOTTLE KEEP CALM,12,6.84,United Kingdom
55,297066,6379318,Tue Feb 12 06:18:00 IST 2019,492513,OVAL MINI PORTRAIT FRAME,24,2.70,United Kingdom

In [22]:
data[:]   #Gives the total records

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
0,278166,6355745,Sat Feb 02 12:50:00 IST 2019,465549,FAMILY ALBUM WHITE PICTURE FRAME,6,11.73,United Kingdom
1,337701,6283376,Wed Dec 26 09:06:00 IST 2018,482370,LONDON BUS COFFEE MUG,3,3.52,United Kingdom
2,267099,6385599,Fri Feb 15 09:45:00 IST 2019,490728,SET 12 COLOUR PENCILS DOLLY GIRL,72,0.90,France
3,380478,6044973,Fri Jun 22 07:14:00 IST 2018,459186,UNION JACK FLAG LUGGAGE TAG,3,1.73,United Kingdom
4,-1,6143225,Mon Sep 10 11:58:00 IST 2018,1733592,WASHROOM METAL SIGN,3,3.40,United Kingdom
...,...,...,...,...,...,...,...,...
1083813,313131,6040298,Mon Jun 18 09:18:00 IST 2018,437976,DENIM PATCH PURSE PINK BUTTERFLY,30,2.28,EIRE
1083814,295743,6387117,Sat Feb 16 09:14:00 IST 2019,484113,RECYCLED ACAPULCO MAT PINK,6,11.39,United Kingdom
1083815,-1,6361817,Tue Feb 05 05:26:00 IST 2019,497595,DOILY THANK YOU CARD,15,1.15,United Kingdom
1083816,324765,5945500,Fri Mar 23 06:26:00 IST 2018,470883,REGENCY CAKESTAND 3 TIER,48,15.12,United Kingdom
1083817,351645,6118145,Tue Aug 21 08:21:00 IST 2018,471849,HEART OF WICKER SMALL,9,2.28,United Kingdom

In [31]:
data[5000:] #It display starting record from the 5000

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
5000,374661,6381496,Tue Feb 12 15:42:00 IST 2019,465234,ANGEL DECORATION 3 BUTTONS,24,0.58,United Kingdom
5001,276843,5945522,Fri Mar 23 06:50:00 IST 2018,444801,PLEASE ONE PERSON METAL SIGN,144,2.56,United Kingdom
5002,318150,6321953,Fri Jan 18 10:45:00 IST 2019,495201,JUMBO BAG PAISLEY PARK,30,2.88,United Kingdom
5003,339528,6355481,Sat Feb 02 11:42:00 IST 2019,487179,JUMBO BAG APPLES,30,2.88,United Kingdom
5004,-1,6044775,Wed Jun 20 11:44:00 IST 2018,481530,BAKING MOULD HEART MILK CHOCOLATE,6,6.85,United Kingdom
...,...,...,...,...,...,...,...,...
1083813,313131,6040298,Mon Jun 18 09:18:00 IST 2018,437976,DENIM PATCH PURSE PINK BUTTERFLY,30,2.28,EIRE
1083814,295743,6387117,Sat Feb 16 09:14:00 IST 2019,484113,RECYCLED ACAPULCO MAT PINK,6,11.39,United Kingdom
1083815,-1,6361817,Tue Feb 05 05:26:00 IST 2019,497595,DOILY THANK YOU CARD,15,1.15,United Kingdom
1083816,324765,5945500,Fri Mar 23 06:26:00 IST 2018,470883,REGENCY CAKESTAND 3 TIER,48,15.12,United Kingdom
1083817,351645,6118145,Tue Aug 21 08:21:00 IST 2018,471849,HEART OF WICKER SMALL,9,2.28,United Kingdom

In [25]:
data[:-5]   #It will display all the records

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
0,278166,6355745,Sat Feb 02 12:50:00 IST 2019,465549,FAMILY ALBUM WHITE PICTURE FRAME,6,11.73,United Kingdom
1,337701,6283376,Wed Dec 26 09:06:00 IST 2018,482370,LONDON BUS COFFEE MUG,3,3.52,United Kingdom
2,267099,6385599,Fri Feb 15 09:45:00 IST 2019,490728,SET 12 COLOUR PENCILS DOLLY GIRL,72,0.90,France
3,380478,6044973,Fri Jun 22 07:14:00 IST 2018,459186,UNION JACK FLAG LUGGAGE TAG,3,1.73,United Kingdom
4,-1,6143225,Mon Sep 10 11:58:00 IST 2018,1733592,WASHROOM METAL SIGN,3,3.40,United Kingdom
...,...,...,...,...,...,...,...,...
1083808,355488,6160286,Tue Sep 25 09:11:00 IST 2018,478191,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,72,1.73,United Kingdom
1083809,321531,6037493,Sat Jun 16 09:57:00 IST 2018,441693,JUMBO BAG CHARLIE AND LOLA TOYS,6,2.88,United Kingdom
1083810,-1,6106650,Sun Aug 12 11:53:00 IST 2018,446040,BLUE POLKADOT CUP,6,2.25,United Kingdom
1083811,352191,5973242,Mon Apr 16 10:37:00 IST 2018,466599,LOVEBIRD HANGING DECORATION WHITE,24,1.18,United Kingdom
1083812,261681,6153092,Wed Sep 19 06:23:00 IST 2018,477330,ALARM CLOCK BAKELIKE IVORY,12,5.18,Switzerland

In [30]:
data[::-1]    #it diplay the record in reverse order

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
1083817,351645,6118145,Tue Aug 21 08:21:00 IST 2018,471849,HEART OF WICKER SMALL,9,2.28,United Kingdom
1083816,324765,5945500,Fri Mar 23 06:26:00 IST 2018,470883,REGENCY CAKESTAND 3 TIER,48,15.12,United Kingdom
1083815,-1,6361817,Tue Feb 05 05:26:00 IST 2019,497595,DOILY THANK YOU CARD,15,1.15,United Kingdom
1083814,295743,6387117,Sat Feb 16 09:14:00 IST 2019,484113,RECYCLED ACAPULCO MAT PINK,6,11.39,United Kingdom
1083813,313131,6040298,Mon Jun 18 09:18:00 IST 2018,437976,DENIM PATCH PURSE PINK BUTTERFLY,30,2.28,EIRE
...,...,...,...,...,...,...,...,...
4,-1,6143225,Mon Sep 10 11:58:00 IST 2018,1733592,WASHROOM METAL SIGN,3,3.40,United Kingdom
3,380478,6044973,Fri Jun 22 07:14:00 IST 2018,459186,UNION JACK FLAG LUGGAGE TAG,3,1.73,United Kingdom
2,267099,6385599,Fri Feb 15 09:45:00 IST 2019,490728,SET 12 COLOUR PENCILS DOLLY GIRL,72,0.90,France
1,337701,6283376,Wed Dec 26 09:06:00 IST 2018,482370,LONDON BUS COFFEE MUG,3,3.52,United Kingdom
0,278166,6355745,Sat Feb 02 12:50:00 IST 2019,465549,FAMILY ALBUM WHITE PICTURE FRAME,6,11.73,United Kingdom

In [29]:
data[::3]  #It diplays the 3 multiples record

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
0,278166,6355745,Sat Feb 02 12:50:00 IST 2019,465549,FAMILY ALBUM WHITE PICTURE FRAME,6,11.73,United Kingdom
3,380478,6044973,Fri Jun 22 07:14:00 IST 2018,459186,UNION JACK FLAG LUGGAGE TAG,3,1.73,United Kingdom
6,345954,6162981,Fri Sep 28 10:51:00 IST 2018,471576,NATURAL SLATE CHALKBOARD LARGE,9,6.84,United Kingdom
9,328440,6387425,Sat Feb 16 10:35:00 IST 2019,494802,SET OF 6 RIBBONS PERFECTLY PRETTY,36,3.99,United Kingdom
12,364791,6358242,Sun Feb 03 09:25:00 IST 2019,486276,SET OF 5 MINI GROCERY MAGNETS,3,2.88,United Kingdom
...,...,...,...,...,...,...,...,...
1083804,-1,6272057,Wed Dec 19 11:09:00 IST 2018,458031,HANGING HEART WITH BELL,24,1.15,United Kingdom
1083807,321531,6044962,Fri Jun 22 07:11:00 IST 2018,477813,SMALL YELLOW BABUSHKA NOTEBOOK,6,1.18,United Kingdom
1083810,-1,6106650,Sun Aug 12 11:53:00 IST 2018,446040,BLUE POLKADOT CUP,6,2.25,United Kingdom
1083813,313131,6040298,Mon Jun 18 09:18:00 IST 2018,437976,DENIM PATCH PURSE PINK BUTTERFLY,30,2.28,EIRE
1083816,324765,5945500,Fri Mar 23 06:26:00 IST 2018,470883,REGENCY CAKESTAND 3 TIER,48,15.12,United Kingdom

In [34]:
user_id = data[data['UserId'] == 278166]      #  Data whose userid is 278166
user_id

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
0,278166,6355745,Sat Feb 02 12:50:00 IST 2019,465549,FAMILY ALBUM WHITE PICTURE FRAME,6,11.73,United Kingdom
1049,278166,6088357,Sun Jul 29 08:38:00 IST 2018,487284,CHARLOTTE BAG APPLES DESIGN,30,1.18,United Kingdom
3886,278166,6088357,Sun Jul 29 08:38:00 IST 2018,474495,GINGHAM HEART DECORATION,6,1.18,United Kingdom
4517,278166,5988884,Fri May 04 06:51:00 IST 2018,435099,WOODLAND CHARLOTTE BAG,300,1.00,United Kingdom
6057,278166,6088357,Sun Jul 29 08:38:00 IST 2018,443394,LAVENDER SCENTED FABRIC HEART,12,1.73,United Kingdom
...,...,...,...,...,...,...,...,...
1072200,278166,5952034,Tue Mar 27 09:36:00 IST 2018,445872,STRAWBERRY CERAMIC TRINKET BOX,24,1.73,United Kingdom
1072716,278166,6355745,Sat Feb 02 12:50:00 IST 2019,460572,SCANDINAVIAN PAISLEY PICNIC BAG,3,2.28,United Kingdom
1074752,278166,5952034,Tue Mar 27 09:36:00 IST 2018,435834,RETROSPOT RED WASHING UP GLOVES,6,2.90,United Kingdom
1075310,278166,6088357,Sun Jul 29 08:38:00 IST 2018,471849,HEART OF WICKER SMALL,360,2.01,United Kingdom
1076084,278166,6088357,Sun Jul 29 08:38:00 IST 2018,1787079,JUMBO BAG RED RETROSPOT,6,2.88,United Kingdom

In [59]:
Customer_country = data[data['Country'] == "Spain"]      #  Data whose country is spain
Customer_country

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
133,263319,6021257,Sun Jun 03 12:00:00 IST 2018,484029,RECYCLED ACAPULCO MAT RED,6,11.39,Spain
224,262542,6072440,Wed Jul 18 04:19:00 IST 2018,477267,ALARM CLOCK BAKELIKE RED,12,5.18,Spain
292,359037,5919045,Tue Feb 20 10:55:00 IST 2018,477246,ALARM CLOCK BAKELIKE GREEN,6,5.18,Spain
429,263571,5932861,Wed Feb 28 07:23:00 IST 2018,1787079,JUMBO BAG BAROQUE BLACK WHITE,30,2.70,Spain
442,262164,6320050,Wed Jan 16 11:18:00 IST 2019,787059,CUBIC MUG FLOCK PINK ON BROWN,36,0.54,Spain
...,...,...,...,...,...,...,...,...
1082691,263340,6070548,Mon Jul 16 12:29:00 IST 2018,459480,RED RETROSPOT TAPE,36,0.90,Spain
1082732,264537,6352753,Fri Feb 01 09:33:00 IST 2019,448140,CLASSIC METAL BIRDCAGE PLANT HOLDER,3,17.60,Spain
1082869,263340,6024733,Tue Jun 05 13:10:00 IST 2018,445452,PACK OF 72 RETROSPOT CAKE CASES,72,0.76,Spain
1083068,263340,6326584,Sun Jan 20 11:38:00 IST 2019,466431,WOOD STAMP SET FLOWERS,36,1.15,Spain
1083173,263445,6025690,Wed Jun 06 08:04:00 IST 2018,443646,SET OF 6 GIRLS CELEBRATION CANDLES,36,1.73,Spain

In [50]:
ACcost_item = data[(data['CostPerItem'] >= 0) & (data['CostPerItem'] <= 10)]      #  Data whose price bw 0 to 10 
cost_item

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
1,337701,6283376,Wed Dec 26 09:06:00 IST 2018,482370,LONDON BUS COFFEE MUG,3,3.52,United Kingdom
2,267099,6385599,Fri Feb 15 09:45:00 IST 2019,490728,SET 12 COLOUR PENCILS DOLLY GIRL,72,0.90,France
3,380478,6044973,Fri Jun 22 07:14:00 IST 2018,459186,UNION JACK FLAG LUGGAGE TAG,3,1.73,United Kingdom
4,-1,6143225,Mon Sep 10 11:58:00 IST 2018,1733592,WASHROOM METAL SIGN,3,3.40,United Kingdom
5,285957,6307136,Fri Jan 11 09:50:00 IST 2019,1787247,CUT GLASS T-LIGHT HOLDER OCTAGON,12,3.52,United Kingdom
...,...,...,...,...,...,...,...,...
1083811,352191,5973242,Mon Apr 16 10:37:00 IST 2018,466599,LOVEBIRD HANGING DECORATION WHITE,24,1.18,United Kingdom
1083812,261681,6153092,Wed Sep 19 06:23:00 IST 2018,477330,ALARM CLOCK BAKELIKE IVORY,12,5.18,Switzerland
1083813,313131,6040298,Mon Jun 18 09:18:00 IST 2018,437976,DENIM PATCH PURSE PINK BUTTERFLY,30,2.28,EIRE
1083815,-1,6361817,Tue Feb 05 05:26:00 IST 2019,497595,DOILY THANK YOU CARD,15,1.15,United Kingdom
1083817,351645,6118145,Tue Aug 21 08:21:00 IST 2018,471849,HEART OF WICKER SMALL,9,2.28,United Kingdom

In [51]:
Item_code = data[data['ItemCode'] == 459480]      #  Data whose Itemcode is 459480
Item_code

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
544,-1,6263092,Sat Dec 15 12:04:00 IST 2018,459480,RED RETROSPOT TAPE,9,0.58,United Kingdom
5273,287574,5932377,Tue Feb 27 13:43:00 IST 2018,459480,RED RETROSPOT TAPE,360,0.27,United Kingdom
12515,358050,6035832,Fri Jun 15 10:42:00 IST 2018,459480,RED RETROSPOT TAPE,18,0.90,United Kingdom
16698,349797,6031399,Mon Jun 11 08:02:00 IST 2018,459480,RED RETROSPOT TAPE,3,0.90,United Kingdom
17651,261723,6129552,Wed Aug 29 10:28:00 IST 2018,459480,RED RETROSPOT TAPE,36,0.90,Belgium
...,...,...,...,...,...,...,...,...
1079785,262017,6270022,Wed Dec 19 05:16:00 IST 2018,459480,RED RETROSPOT TAPE,36,0.90,Germany
1080282,378861,6211975,Fri Nov 09 08:28:00 IST 2018,459480,RED RETROSPOT TAPE,3,0.90,United Kingdom
1080584,266070,6217629,Wed Nov 14 05:51:00 IST 2018,459480,RED RETROSPOT TAPE,36,0.90,France
1082189,265377,6051595,Tue Jun 26 10:15:00 IST 2018,459480,RED RETROSPOT TAPE,36,0.90,France
1082691,263340,6070548,Mon Jul 16 12:29:00 IST 2018,459480,RED RETROSPOT TAPE,36,0.90,Spain

In [63]:
Country_bw = data[(data['Country'] == "Spain") | (data['Country'] == "France")]      #  Data whose country is spain "OR" france 
Country_bw

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
2,267099,6385599,Fri Feb 15 09:45:00 IST 2019,490728,SET 12 COLOUR PENCILS DOLLY GIRL,72,0.90,France
22,262269,5945093,Wed Mar 21 09:13:00 IST 2018,474726,WOODEN SKITTLES GARDEN SET,6,22.02,France
74,267183,6266689,Mon Dec 17 11:52:00 IST 2018,489699,BOX OF 6 MINI 50'S CRACKERS,6,3.44,France
133,263319,6021257,Sun Jun 03 12:00:00 IST 2018,484029,RECYCLED ACAPULCO MAT RED,6,11.39,Spain
154,266301,5970085,Sat Apr 14 11:36:00 IST 2018,-1,POSTAGE,9,24.84,France
...,...,...,...,...,...,...,...,...
1083498,263613,6024942,Wed Jun 06 06:19:00 IST 2018,1765617,WORLD WAR 2 GLIDERS ASSTD DESIGNS,144,0.41,France
1083531,266049,6156744,Sun Sep 23 05:54:00 IST 2018,475188,PICNIC BOXES SET OF 3 RETROSPOT,12,6.84,France
1083553,262269,5945093,Wed Mar 21 09:13:00 IST 2018,471429,SILK PURSE BABUSHKA PINK,18,4.63,France
1083629,263907,6095067,Fri Aug 03 09:01:00 IST 2018,470022,LUNCH BAG SPACEBOY DESIGN,30,2.28,France
1083782,266994,6377712,Mon Feb 11 11:43:00 IST 2019,468846,ROUND SNACK BOXES SET OF4 WOODLAND,36,4.08,France

In [62]:
# Display data which item description contains "RED RETROSPOT TAPE" word
ItemDescription = data[data['ItemDescription'] == "WASHROOM METAL SIGN"]
ItemDescription

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
4,-1,6143225,Mon Sep 10 11:58:00 IST 2018,1733592,WASHROOM METAL SIGN,3,3.40,United Kingdom
1414,298431,5995825,Sat May 12 05:33:00 IST 2018,1733592,WASHROOM METAL SIGN,36,2.01,United Kingdom
3254,308931,6021070,Sun Jun 03 09:32:00 IST 2018,1733592,WASHROOM METAL SIGN,3,2.01,United Kingdom
3409,340662,5963177,Sun Apr 08 09:38:00 IST 2018,1733592,WASHROOM METAL SIGN,18,2.01,United Kingdom
8956,361011,5911400,Sat Feb 17 10:36:00 IST 2018,1733592,WASHROOM METAL SIGN,3,2.01,United Kingdom
...,...,...,...,...,...,...,...,...
1080947,278649,5907638,Fri Feb 16 07:51:00 IST 2018,1733592,WASHROOM METAL SIGN,36,2.01,United Kingdom
1081972,322476,5985683,Mon Apr 30 08:11:00 IST 2018,1733592,WASHROOM METAL SIGN,6,2.01,United Kingdom
1082005,332976,6212085,Fri Nov 09 09:35:00 IST 2018,1733592,WASHROOM METAL SIGN,18,2.01,United Kingdom
1082029,-1,6213185,Sun Nov 11 08:31:00 IST 2018,1733592,WASHROOM METAL SIGN,3,3.40,United Kingdom
1083585,268044,5965036,Tue Apr 10 06:19:00 IST 2018,1733592,WASHROOM METAL SIGN,36,2.01,Lebanon